axf/App/urls.py
from django.conf.urls import url
from App.views import *
urlpatterns = [
    # 首页路由地址
    url(r'^$',home.index),
    url(r'^home/$',home.index,name='home'),
    # 闪送超时的样式
    # 无参
    url(r'^market/$',market.market,name='market'),
    # 构造带参数的
    url(r'^market/(\d+)/(\d+)/(\d+)/$',market.market,name='market2'),
    # 购物车
    url(r'^car/$',car.car,name='car'),
    # 购物数量+ - 的操作
    url(r'^doCar/$',car.doCar,name='doCar'),
    # 当选中下单 进行查看是否有选中商品时的操作
    url(r'^findChoose/$',car.findChoose,name='findChoose'),
    # 我的路由地址
    url(r'^mine/$',mine.mine,name='mine'),
    # 注册
    url(r'^register/$',mine.Register,name='register'),
    # 登录
    url(r'^login/$',mine.Login,name='login'),
    # 退出登录
    url(r'^logout/$',mine.Logout,name='logout'),
    # 订单显示页面
    url(r'^order/$',order.order,name='order'),
    # 处理下订单
    url(r'^doOrder/$',order.doOrder,name='doOrder'),
]

axf/axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('App.urls',namespace='App')),
]

axf/App/views/order.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from App.models import Order,Car,Address,OrderDetail


# 展示订单详情页
def order(req):
    # 查询默认选中的地址数据
    address = Address.objects.filter(state=True).first()
    # print(address)
    # 查询购物车选中的商品
    carObj = Car.objects.filter(isChoose=True)
    # 计算总价
    money = 0
    for car in carObj:
        money += car.num * eval(car.goods.price)
    return render(req,'order/order.html',{'address':address,'carObj':carObj,'money':'%.2f'%money})

import time
# 处理的操作
def doOrder(req):
    addressId = int(req.POST.get('addressId'))
    money = req.POST.get('money')
    message = req.POST.get('message')
    # 将订单数据存储到表单中
    addressObj = Address.objects.get(pk=addressId)
    orderObj = Order()
    orderObj.user = req.user
    orderObj.address = addressObj
    orderObj.money = money
    orderObj.message = message
    orderObj.orderId = time.strftime('%y%m%d')
    orderObj.save()
    # 先获取到购物车选中的商品
    carObj = Car.objects.filter(isChoose = True)
    # 迭代获取到每一个对象
    for car in carObj:
        # 生成订单详情
        OrderDetail(order=orderObj,goodsImg=car.goods.productimg,goodsName=car.goods.productname,price=car.goods.price,num=car.num,total=car.num*eval(car.goods.price)).save()
    return redirect(reverse('App:car'))

axf/templates/order/order.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}

{% block linkscript%}
    <link rel="stylesheet" type="text/css" href="{% static 'car/css/cart.css' %}" />
{% endblock linkscript%}

{% block base %}
<div id="cart">
    <h3><b>购物车</b></h3>
    <form action="{% url 'App:doOrder' %}" method="post" id="myForm">
    {% csrf_token %}
    <section class="full">
        <input type="hidden" name="addressId" value="{{ address.id }}">
        <input type="hidden" name="money" value="{{ money }}">
		<section>
			<ul>
				<li>
                    <div class="clear">
                        <p class="infoJustify">收货人<b></b></p><p>:<span>{{ address.name }}</span></p>
                    </div>
                </li>
				<li>
                    <div class="clear">
                        <p class="infoJustify">电话<b></b></p><p>:<span>{{ address.phone }}</span><a class="change">修改></a></p>
                    </div>
                </li>
				<li>
                    <div class="clear"><p class="infoJustify">收货地址<b></b></p><p>:<span>{{ address.address }}</span></p>
                    </div>
                </li>
			</ul>


			<section class="bill">
				<p>闪送超市</p>
				<p>¥0起送,22:00前满¥30免运费</p>
				<a>凑单专区</a>
			</section>


			<section class="delivery">
				<span>收货时间</span> <span>一小时送达</span> <a>可预订></a>
			</section>
			<section class="delivery">
				<span>收货备注</span> <input type="text" name="message" placeholder="可输入100字以内特殊要求内容"/>
			</section>


            <menu>
				<ul>
                    {% for item in carObj%}
                    <li id="{{item.productid}}li" class="menuList">
                        <div class="confirm">
                            <span class="ischose">
                                <span>
                                √
                                </span>
                            </span>
                        </div>
                        <a href="#">
                            <img src="{{item.goods.productimg}}"/>
                            <p>{{item.goods.productname}}</p>
                            <span>{{item.goods.price}}</span>
                        </a>
                        <section>
{#                            <button class="subShopping"  ga="{{item.productid}}">-</button>#}
                            <span id="{{item.productid}}">{{item.num}}</span>
{#                            <button class="addShopping"  ga="{{item.productid}}">+</button>#}
                        </section>
                    </li>
                    {% endfor %}

					<li class="payTheBill">
						<p><span>共计:</span><span>总价:{{ money }}元</span></p>
						<a id="ok" onclick="document.getElementById('myForm').submit();">下单</a>
					</li>
				</ul>
			</menu>
		</section>
	</section>
    </form>
</div>
{% endblock base %}