axf/App/urls.py
from django.conf.urls import url
from App.views import *
urlpatterns = [
    # 首页路由地址
    url(r'^$',home.index),
    url(r'^home/$',home.index,name='home'),
    # 闪送超时的样式
    # 无参
    url(r'^market/$',market.market,name='market'),
    # 构造带参数的
    url(r'^market/(\d+)/(\d+)/(\d+)/$',market.market,name='market2'),
    # 购物车
    url(r'^car/$',car.car,name='car'),
    # 购物数量+ - 的操作
    url(r'^doCar/$',car.doCar,name='doCar'),
    # 当选中下单 进行查看是否有选中商品时的操作
    url(r'^findChoose/$',car.findChoose,name='findChoose'),
    # 我的路由地址
    url(r'^mine/$',mine.mine,name='mine'),
    # 注册
    url(r'^register/$',mine.Register,name='register'),
    # 登录
    url(r'^login/$',mine.Login,name='login'),
    # 退出登录
    url(r'^logout/$',mine.Logout,name='logout'),
    # 订单显示页面
    url(r'^order/$',order.order,name='order'),
    # 处理下订单
    url(r'^doOrder/$',order.doOrder,name='doOrder'),
]

axf/axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('App.urls',namespace='App')),
]

axf/templates/common/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">

    <link rel="stylesheet" type="text/css" href="{% static 'common/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/swiper.min.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/reset.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/base.css'%}" />

    <script type="text/javascript" charset="utf-8" src="{% static 'common/js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'common/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'common/js/swiper.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'common/js/base.js' %}"></script>

    {% block linkscript %}
    {% endblock linkscript %}

</head>
<body>
    <header></header>

    <div>
        {% block base %}
        {% endblock base %}
    </div>

    <footer>
        <a class="home" href="{% url 'App:home' %}">
            <dl>
                <dt><span></span></dt>
                <dd>主页</dd>
            </dl>
        </a>
        <a class="market" href="{% url 'App:market' %}">
            <dl>
                <dt><span></span></dt>
                <dd>闪送超市</dd>
            </dl>
        </a>
        <a class="cart" href="/car/">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a class="mine" href="{% url 'App:mine' %}">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
</body>
</html>