axf/App/urls.py
from django.conf.urls import url
from App.views import *
urlpatterns = [
    # 首页路由地址
    url(r'^$',home.index),
    url(r'^home/$',home.index,name='home'),
    # 闪送超时的样式
    # 无参
    url(r'^market/$',market.market,name='market'),
    # 构造带参数的
    url(r'^market/(\d+)/(\d+)/(\d+)/$',market.market,name='market2'),
    # 购物车
    url(r'^car/$',car.car,name='car'),
    # 购物数量+ - 的操作
    url(r'^doCar/$',car.doCar,name='doCar'),
    # 当选中下单 进行查看是否有选中商品时的操作
    url(r'^findChoose/$',car.findChoose,name='findChoose'),
    # 我的路由地址
    url(r'^mine/$',mine.mine,name='mine'),
    # 注册
    url(r'^register/$',mine.Register,name='register'),
    # 登录
    url(r'^login/$',mine.Login,name='login'),
    # 退出登录
    url(r'^logout/$',mine.Logout,name='logout'),
    # 订单显示页面
    url(r'^order/$',order.order,name='order'),
    # 处理下订单
    url(r'^doOrder/$',order.doOrder,name='doOrder'),
]

axf/axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('App.urls',namespace='App')),
]

axf/App/views/mine.py
from django.shortcuts import render,redirect,reverse,HttpResponse
from django.contrib.auth import login,logout,authenticate
from App.models import User


def mine(req):
    return render(req,'mine/mine.html')


# 注册
def Register(req):
    if req.method == 'POST':
        username = req.POST.get('userAccount')
        userpass = req.POST.get('userPass')
        email = req.POST.get('email')
        u = User.objects.create_user(username,email,userpass)
        u.save()
        return redirect(reverse('App:login'))
    return render(req,'mine/register.html')


# 登录
def Login(req):
    if req.method == 'POST':
        username = req.POST.get('userAccount')
        userpass = req.POST.get('userPass')
        u = authenticate(username=username, password=userpass)
        if u:
            if u.is_active:
                login(req,u)
                print('登录成功')
                return redirect(reverse('App:mine'))
        return HttpResponse('请输入正确的用户或者密码')
    return render(req,'mine/login.html')


# 退出登录
def Logout(req):
    logout(req)
    return redirect(reverse('App:mine'))

axf/templates/mine/login.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}
{% block linkscript%}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/register.css' %}" />
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/register.js' %}" ></script>
{% endblock linkscript%}


{% block base %}
<div id="register">
    <div id="header">
        <a href="/mine/"><p>&lt;返回</p></a>
    </div>
    <form class="form-horizontal" action="{% url 'App:login' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="input-group">
            <span class="input-group-addon">账号</span>
            <input id="accunt" type="text" class="form-control" placeholder="账号长度为6到12个字符" aria-describedby="basic-addon1" name="userAccount">
        </div>
        <span id="accunterr" class="error">账号格式输入错误</span>
        <span id="checkerr" class="error">账号已被占用，请重新输入</span>
        <br/>
        <div class="input-group">
            <span class="input-group-addon">密码</span>
            <input id="pass" type="password" class="form-control" placeholder="密码长度为6~16个字符" aria-describedby="basic-addon1" name="userPass">
        </div>
        <span id="passerr" class="error">密码格式输入错误</span>
        <br />
        <div class="input-group">
            <span class="input-group-addon">登录</span>
            <input type="submit" class="form-control" aria-describedby="basic-addon1" value="登录">
        </div>
    </form>
</div>
{% endblock base %}

axf/templates/mine/mine.html
{% extends 'common/base.html' %}
{% load static %}
{% block linkscript %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{#    <script src="{% static 'mine/js/mine.js' %}"></script>#}
{% endblock %}
{% block base %}
<div id="mine">
    <section class="fixed">
		<span class="glyphicon glyphicon-user"></span>
        {% if request.user.is_authenticated %}
                <p><a href="{% url 'App:logout' %}">{{ request.user.username }}  退出登录</a></p>
        {% else %}
                <p><a href="{% url 'App:login' %}">登录 </a></p>
                <a id="regis" href="{% url 'App:register' %}">注册</a>
        {% endif %}
{#		<p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>#}
		<p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
	</section>

    <section class="mine">
		<p>
			<span>我的订单</span><a>查看全部订单&gt;</a>
		</p>
		<nav id="nav">
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-usd"></span></dt>
							<dd>代付款</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-envelope"></span></dt>
							<dd>待收货</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-pencil"></span></dt>
							<dd>待评价</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-retweet"></span></dt>
							<dd>退款/售后</dd>
						</dl>
					</a>
				</li>
			</ul>
		</nav>


		<menu>
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
							<dd>积分商城</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-credit-card"></span></dt>
							<dd>优惠券</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-import"></span></dt>
							<dd>收货地址</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
							<dd>客服/反馈</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-asterisk"></span></dt>
							<dd>关于我们</dd>
						</dl>
					</a>
				</li>
			</ul>
		</menu>
		<p><a href="/quit/">退出当前账号</a></p>
	</section>
</div>
{% endblock %}

axf/templates/mine/register.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}
{% block linkscript%}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/register.css' %}" />
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/register.js' %}" ></script>
{% endblock linkscript%}


{% block base %}
<div id="register">
    <div id="header">
        <a href="/mine/"><p>&lt;返回</p></a>
    </div>
    <form class="form-horizontal" action="{% url 'App:register' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="input-group">
            <span class="input-group-addon">账号</span>
            <input id="accunt" type="text" class="form-control" placeholder="账号长度为6到12个字符" aria-describedby="basic-addon1" name="userAccount">
        </div>
        <span id="accunterr" class="error">账号格式输入错误</span>
        <span id="checkerr" class="error">账号已被占用，请重新输入</span>
        <br/>
        <div class="input-group">
            <span class="input-group-addon">密码</span>
            <input id="pass" type="password" class="form-control" placeholder="密码长度为6~16个字符" aria-describedby="basic-addon1" name="userPass">
        </div>
        <span id="passerr" class="error">密码格式输入错误</span>
        <br />
        <div class="input-group">
            <span class="input-group-addon">验证</span>
            <input id="passwd" type="password" class="form-control" placeholder="密码长度为6~16个字符" aria-describedby="basic-addon1" name="userPasswd">
        </div>
        <span id="passwderr" class="error">两次密码输入不同</span>
        <br/>
        <div class="input-group">
            <span class="input-group-addon">邮箱</span>
            <input type="email" class="form-control" placeholder="输入邮箱地址" aria-describedby="basic-addon1" name="email">
        </div>
        <br>
        <div class="input-group">
            <span class="input-group-addon">注册</span>
            <input type="submit" class="form-control" aria-describedby="basic-addon1" value="注册">
        </div>
    </form>
</div>
{% endblock base %}