axf/App/urls.py
from django.conf.urls import url
from App.views import *
urlpatterns = [
    # 首页路由地址
    url(r'^$',home.index),
    url(r'^home/$',home.index,name='home'),
    # 闪送超时的样式
    # 无参
    url(r'^market/$',market.market,name='market'),
    # 构造带参数的
    url(r'^market/(\d+)/(\d+)/(\d+)/$',market.market,name='market2'),
    # 购物车
    url(r'^car/$',car.car,name='car'),
    # 购物数量+ - 的操作
    url(r'^doCar/$',car.doCar,name='doCar'),
    # 当选中下单 进行查看是否有选中商品时的操作
    url(r'^findChoose/$',car.findChoose,name='findChoose'),
    # 我的路由地址
    url(r'^mine/$',mine.mine,name='mine'),
    # 注册
    url(r'^register/$',mine.Register,name='register'),
    # 登录
    url(r'^login/$',mine.Login,name='login'),
    # 退出登录
    url(r'^logout/$',mine.Logout,name='logout'),
    # 订单显示页面
    url(r'^order/$',order.order,name='order'),
    # 处理下订单
    url(r'^doOrder/$',order.doOrder,name='doOrder'),
]

axf/axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('App.urls',namespace='App')),
]

axf/App/views/market.py
from django.shortcuts import render,HttpResponse
from App.models import FoodTypes,Goods

# 闪送超市的样式
# categoryid是商品表里的类别id  在foodtypes表里叫typeid
# childcid商品表中 子类别的id
# orderby 按照某个值进行排序
def market(req,categoryid=104749,childcid=0,orderby=0):
    footTypeData = FoodTypes.objects.all()
    # 查询右侧商品数据
    # 判断是否查询当前类别的所有商品还是查询当前类别子类的商品
    goodsData = Goods.objects.filter(categoryid=categoryid)
    if int(childcid):
        goodsData = goodsData.filter(childcid=childcid)

    # 对商品根据传递进来的orderby参数值进行排序
    orderby = int(orderby)
    # 销量
    if orderby == 1:
        goodsData = goodsData.order_by('-productnum')
    #  价格最低
    elif orderby == 2:
        goodsData = goodsData.order_by('price')
    #     价格最高
    elif orderby == 3:
        goodsData = goodsData.order_by('-price')

    # 通过左侧类别的查询 查询出当前类别的子类 在goods表中叫childcid也就是foodtype表中的childtypenames的数据
    childCidData = footTypeData.filter(typeid=categoryid).first().childtypenames
    # print(childCidData)
    # 迭代获取 其中的名字和id的二维列表
    # 按照# 号进行拆分每一对类别名称和id
    childCidDataList = childCidData.split('#')
    childCidList = []
    # 拿到每一对的类别名称和id
    for typeStr in childCidDataList:
        # 将每一对类别名称和id再次进行拆分成列表
        childCidList.append(typeStr.split(':'))
    # print(childCidList)
    return render(req,'market/market.html',{'footTypeData':footTypeData,'goodsData':goodsData,'childCidList':childCidList,'categoryid':categoryid,'childcid':childcid})

axf/templates/market/market.html
{% extends 'common/base.html' %}
{% load static %}
{% block linkscript %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}
{% block base %}
<div id="market">
    {# 左侧总类别显示的样式 #}
    <aside>
        <menu>
            <ul>
                {% for item in footTypeData %}
                <li>
                    <span class="yellowSlide"></span>
                    <a href="{% url 'App:market2' item.typeid 0 0 %}">{{item.typename}}</a>
                </li>
                {% endfor %}
            </ul>
        </menu>
    </aside>
    <section>
        <nav>
            <ul>
                <li><span id="alltypebtn">全部类型<span class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span></span></li>
				<li><span id="showsortbtn">综合排序<span class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span></span></li>
            </ul>
        </nav>
        {#   商品数据样式     #}
        <menu>
            <ul>
                {% for item in goodsData %}
                <li>
                    <a href="#">
                        <img src="{{item.productimg}}" />
                        <article class="shoppingInfo">
                            <h6>{{item.productlongname}}</h6>
                            <p class="detailTag"><span>精选</span><span>{{item.pedesc}}</span></p>
                            <span class="unit">{{item.specifics}}</span>
                            <p class="price"><span>￥{{item.price}}</span><s><span>￥{{item.marketprice}}</span></s></p>
                        </article>
                    </a>
                    <section>
						<button class="subShopping" onclick="doCar({{ item.id }},0);">-</button>
                        <span id="{{item.id}}">{{item.num|default:0}}</span>
						<button class="addShopping" onclick="doCar({{ item.id }},1);">+</button>
					</section>
                </li>
                {% endfor %}
            </ul>
            {#   通过父类查询子类数据的样式     #}
            <div id="typediv">
                <div>
                    {% for item in childCidList %}
                    <a href="{% url 'App:market2' categoryid item.1 0 %}"><span>{{item.0}}</span></a>
                    {% endfor %}
                </div>
            </div>
            {#      二次筛选的排序      #}
            <div id="sortdiv">
                <div>
                    <a href="{% url 'App:market2' categoryid childcid 0 %}" class="sorta"><span>综合排序</span></a>
                    <a href="{% url 'App:market2' categoryid childcid 1 %}" class="sorta"><span>销量排序</span></a>
                    <a href="{% url 'App:market2' categoryid childcid 2 %}" class="sorta"><span>价格最低</span></a>
                    <a href="{% url 'App:market2' categoryid childcid 3 %}" class="sorta"><span>价格最高</span></a>
                </div>
            </div>
        </menu>
    </section>
</div>
<script>
    {#  goodsId为商品的自增ID state为状态值 0 商品-1 1为商品+1  #}
    function doCar(goodsId,state) {
        $.get('/doCar/',{'goodsId':goodsId,'state':state},function (data,status){
{#            console.log(data,status);#}
            if(data.code == 500){
                if(window.confirm('您还没有登录 是否前往登录？')){
                    window.location.href = '/login/';
                }
            }else{
                {#      将商品数量更改到节点中      #}
                $('#'+goodsId).html(data.totalNum);
            }
        })
    }
</script>
{% endblock %}